name: Build e Teste Java com Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build com Maven
      run: mvn clean install

    - name: Executar testes
      run: mvn test

